-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.approval
(
    approval_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    approval_status boolean NOT NULL,
    reason character varying(500) COLLATE pg_catalog."default" NOT NULL,
    booking_id character varying(50) COLLATE pg_catalog."default",
    person_id character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT approval_pkey PRIMARY KEY (approval_id),
    CONSTRAINT approval_booking_id_key UNIQUE (booking_id)
);

CREATE TABLE IF NOT EXISTS public.booking
(
    booking_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    booking_status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    purpose character varying(500) COLLATE pg_catalog."default" NOT NULL,
    person_id character varying(50) COLLATE pg_catalog."default",
    time_id character varying(50) COLLATE pg_catalog."default",
    is_cancelled boolean,
    CONSTRAINT booking_pkey PRIMARY KEY (booking_id)
);

CREATE TABLE IF NOT EXISTS public.booking_room
(
    booking_booking_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    room_room_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT booking_room_pkey PRIMARY KEY (booking_booking_id, room_room_id)
);

CREATE TABLE IF NOT EXISTS public.building
(
    building_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    building_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    location character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT building_pkey PRIMARY KEY (building_id)
);

CREATE TABLE IF NOT EXISTS public.department
(
    dept_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dept_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT department_pkey PRIMARY KEY (dept_id)
);

CREATE TABLE IF NOT EXISTS public.person
(
    person_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    person_fname character varying(50) COLLATE pg_catalog."default" NOT NULL,
    specialization character varying(50) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    person_lname character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dept_id character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT person_pkey PRIMARY KEY (person_id)
);

CREATE TABLE IF NOT EXISTS public.person_phone
(
    person_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(8) COLLATE pg_catalog."default" NOT NULL,
    phone_id character varying(50),
    PRIMARY KEY (phone_id)
);

CREATE TABLE IF NOT EXISTS public.room
(
    room_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    capacity integer NOT NULL,
    floor integer NOT NULL,
    building_id character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT room_pkey PRIMARY KEY (room_id)
);

CREATE TABLE IF NOT EXISTS public."time"
(
    time_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    start_time time(0) with time zone NOT NULL,
    end_time time(0) with time zone NOT NULL,
    semester character varying(10) COLLATE pg_catalog."default" NOT NULL,
    year integer NOT NULL,
    date date NOT NULL,
    CONSTRAINT time_pkey PRIMARY KEY (time_id)
);

ALTER TABLE IF EXISTS public.approval
    ADD CONSTRAINT approval_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.booking (booking_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;
CREATE INDEX IF NOT EXISTS approval_booking_id_key
    ON public.approval(booking_id);


ALTER TABLE IF EXISTS public.approval
    ADD CONSTRAINT approval_person_id_fkey FOREIGN KEY (person_id)
    REFERENCES public.person (person_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT booking_person_id_fkey FOREIGN KEY (person_id)
    REFERENCES public.person (person_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT booking_time_id_fkey FOREIGN KEY (time_id)
    REFERENCES public."time" (time_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.booking_room
    ADD CONSTRAINT booking_room_booking_booking_id_fkey FOREIGN KEY (booking_booking_id)
    REFERENCES public.booking (booking_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.booking_room
    ADD CONSTRAINT booking_room_room_room_id_fkey FOREIGN KEY (room_room_id)
    REFERENCES public.room (room_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.person
    ADD CONSTRAINT person_dept_id_fkey FOREIGN KEY (dept_id)
    REFERENCES public.department (dept_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.person_phone
    ADD CONSTRAINT fk_person_phone_person_id FOREIGN KEY (person_id)
    REFERENCES public.person (person_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.room
    ADD CONSTRAINT building_id FOREIGN KEY (building_id)
    REFERENCES public.building (building_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;

END;